In [1]:
# Creating an array
arr = ['one', ' two', 'three']
arr2 = [1, 2, 3]
empty_arr = []
empty_arr_ofshape = [0] * 100 # 100 0
print(len(arr))
print(len(arr2))
print(len(empty_arr))
print(len(empty_arr_ofshape))

3
3
0
100


In [2]:
# Accessing array values via index
print(arr[0])
print(arr[1])
print(arr[2])
#print(arr[3]) This will throw an error index out of bounds

one
 two
three


In [3]:
# Modify array values via index
arr[0] = "New Number"
for item in arr:
    print(item)

New Number
 two
three


In [4]:
# Iterate over an array 
import numpy as np
randnums = np.random.randint(1, 101, 5)
print(randnums)

[78  5  7 41 90]


In [5]:
for i in range(len(randnums)):
    print(randnums[i], end=' ')

78 5 7 41 90 

In [6]:
# another way of iterating over an array 
for item in randnums:
    print(item, end=' ')

78 5 7 41 90 

In [7]:
# List Opperations
# Repetition
rep = ["Dog"] * 3
print( rep)

['Dog', 'Dog', 'Dog']


In [8]:
# Concateination
cat1 = [1,2,3]
cat2 = [4, 5, 6]
cat3 = cat1 + cat2
print(cat1)
print(cat2)
print(cat3)

[1, 2, 3]
[4, 5, 6]
[1, 2, 3, 4, 5, 6]


In [9]:
# Check if a item is present in a list or not (use the 'in' operator)
print(3 in cat3)
print(8 in cat3)

True
False


In [10]:
# Reverse an array of N integers
plan_arr = np.random.randint(1, 101, 5)
print(plan_arr)
lst_idx = len(plan_arr) - 1
num_iter = len(plan_arr)//2 # This is you swap the first and last as the same time
for i in range(0, num_iter):
    temp = plan_arr[lst_idx]
    plan_arr[lst_idx] = plan_arr[i] # move first index number to last number
    plan_arr[i] = temp # move last nubmer to first number
    lst_idx -=1

print(plan_arr)



[79 47 77 25 66]
[66 25 77 47 79]


In [11]:
# This can be done much easier with built in python code
plan_arr = np.random.randint(1, 101, 5)
print(plan_arr)
rev_arr = plan_arr[::-1]
print(rev_arr)

[43 65 86 60 35]
[35 60 86 65 43]


In [12]:
# Simplest way to reverse a list
# NOTE CANNOT BE A NUMPY ARRAY
test_arr = [1,5,8,2]
print(test_arr)
test_arr.reverse()
print(test_arr)

[1, 5, 8, 2]
[2, 8, 5, 1]
